import { ChevronDownIcon } from '@heroicons/react/24/outline';
import { Inter } from 'next/font/google';
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});
export const metadata = {
  title: 'Recently viewed - Figma',
  description: 'Generated by create next app',
};
function page() {
  return (
    <div className={`text-white ${inter.className}`}>
      <div className="p-4 border-[rgb(68,68,68)] border-b bg-[383838]">
        Recently viewed
      </div>
      <div className="flex">
        <div className="border-[rgb(68,68,68)] rounded-lg p-4 m-4 border">
          <p>New design file</p>
        </div>
        <div className="border-[rgb(68,68,68)] rounded-lg p-4 m-4  border">
          <p>New FigJam file</p>
        </div>
        <div className="border-[rgb(68,68,68)] rounded-lg p-4 m-4  border">
          <p>Import file</p>
        </div>
      </div>
      <div className="p-4 flex justify-between">
        <div className="flex items-center space-x-2">
          <p> Filter: All files </p>
          <ChevronDownIcon className="text-white h-3 w-3 " />
        </div>
        <div className="flex items-center space-x-2">
          <p>Sort: Last viewed</p>
          <ChevronDownIcon className="text-white h-3 w-3 " />
        </div>
      </div>
    </div>
  );
}

export default page;
