import React from 'react';
export const metadata = {
  title: 'Recently viewed - Figma',
  description: 'Generated by create next app',
};
function page() {
  return <div className="text-white">Recently viewed</div>;
}

export default page;
