import Header from '@/components/file/Header';
import LeftSidebar from '@/components/file/LeftSidebar';
import RightSidebar from '@/components/file/RightSidebar';

export const metadata = {
  title: 'Recently viewed - Figma',
  description: 'Generated by create next app',
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col bg-[#2c2c2c] overflow-y-hidden  ">
        <Header />
        <div className="w-full flex ">
          <LeftSidebar />
          <div className="flex-1 overflow-y-auto z-0">{children}</div>
          <RightSidebar />
        </div>
      </body>
    </html>
  );
}
