import Header from "../../components/files/Header";
import Sidebar from "../../components/files/Sidebar";
export const metadata = {
  title: "Recently viewed - DesignFlow",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex bg-[#2c2c2c] overflow-y-hidden  ">
        <Sidebar />
        <div className="w-full flex flex-col">
          <Header />
          <div className="flex-1 overflow-y-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
